// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imjasfwignjgnqqauypw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltamFzZndpZ25qZ25xcWF1eXB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMzUxMTQsImV4cCI6MjA1OTgxMTExNH0.kZDFmvhfjEL_Z1QYbeN9IsxLkkYMulATh0l-zHGGIx4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);